.pragma library // can be commented to benefit from LSP, but uncomment before commiting

const target2source = {
  "EN-GB": "EN",
  "EN-US": "EN",
  "ES-419": "ES",
  "PT-BR": "PT",
  "PT-PT": "PT",
  "ZH-HANS": "ZH",
  "ZH-HANT": "ZH",
};

const source2target = {
  "EN": "EN-US",
  "PT": "PT-PT",
  "ZH": "ZH-HANS",
};

const acronym2language = {
  sources: {
    "ACE": "Acehnese",
    "AF": "Afrikaans",
    "AN": "Aragonese",
    "AR": "Arabic",
    "AS": "Assamese",
    "AY": "Aymara",
    "AZ": "Azerbaijani",
    "BA": "Bashkir",
    "BE": "Belarusian",
    "BG": "Bulgarian",
    "BHO": "Bhojpuri",
    "BN": "Bengali",
    "BR": "Breton",
    "BS": "Bosnian",
    "CA": "Catalan",
    "CEB": "Cebuano",
    "CKB": "Kurdish (Sorani)",
    "CS": "Czech",
    "CY": "Welsh",
    "DA": "Danish",
    "DE": "German",
    "EL": "Greek",
    "EN": "English",
    "EO": "Esperanto",
    "ES": "Spanish",
    "ET": "Estonian",
    "EU": "Basque",
    "FA": "Persian",
    "FI": "Finnish",
    "FR": "French",
    "GA": "Irish",
    "GL": "Galician",
    "GN": "Guarani",
    "GOM": "Konkani",
    "GU": "Gujarati",
    "HA": "Hausa",
    "HE": "Hebrew",
    "HI": "Hindi",
    "HR": "Croatian",
    "HT": "Haitian Creole",
    "HU": "Hungarian",
    "HY": "Armenian",
    "ID": "Indonesian",
    "IG": "Igbo",
    "IS": "Icelandic",
    "IT": "Italian",
    "JA": "Japanese",
    "JV": "Javanese",
    "KA": "Georgian",
    "KK": "Kazakh",
    "KMR": "Kurdish (Kurmanji)",
    "KO": "Korean",
    "KY": "Kyrgyz",
    "LA": "Latin",
    "LB": "Luxembourgish",
    "LMO": "Lombard",
    "LN": "Lingala",
    "LT": "Lithuanian",
    "LV": "Latvian",
    "MAI": "Maithili",
    "MG": "Malagasy",
    "MI": "Maori",
    "MK": "Macedonian",
    "ML": "Malayalam",
    "MN": "Mongolian",
    "MR": "Marathi",
    "MS": "Malay",
    "MT": "Maltese",
    "MY": "Burmese",
    "NB": "Norwegian Bokmål",
    "NE": "Nepali",
    "NL": "Dutch",
    "OC": "Occitan",
    "OM": "Oromo",
    "PA": "Punjabi",
    "PAG": "Pangasinan",
    "PAM": "Kapampangan",
    "PL": "Polish",
    "PRS": "Dari",
    "PS": "Pashto",
    "PT": "Portuguese",
    "QU": "Quechua",
    "RO": "Romanian",
    "RU": "Russian",
    "SA": "Sanskrit",
    "SCN": "Sicilian",
    "SK": "Slovak",
    "SL": "Slovenian",
    "SQ": "Albanian",
    "SR": "Serbian",
    "ST": "Sesotho",
    "SU": "Sundanese",
    "SV": "Swedish",
    "SW": "Swahili",
    "TA": "Tamil",
    "TE": "Telugu",
    "TG": "Tajik",
    "TH": "Thai",
    "TK": "Turkmen",
    "TL": "Tagalog",
    "TN": "Tswana",
    "TR": "Turkish",
    "TS": "Tsonga",
    "TT": "Tatar",
    "UK": "Ukrainian",
    "UR": "Urdu",
    "UZ": "Uzbek",
    "VI": "Vietnamese",
    "WO": "Wolof",
    "XH": "Xhosa",
    "YI": "Yiddish",
    "YUE": "Cantonese",
    "ZH": "Chinese",
  },
  targets: {
    "ACE": "Acehnese",
    "AF": "Afrikaans",
    "AN": "Aragonese",
    "AR": "Arabic",
    "AS": "Assamese",
    "AY": "Aymara",
    "AZ": "Azerbaijani",
    "BA": "Bashkir",
    "BE": "Belarusian",
    "BG": "Bulgarian",
    "BHO": "Bhojpuri",
    "BN": "Bengali",
    "BR": "Breton",
    "BS": "Bosnian",
    "CA": "Catalan",
    "CEB": "Cebuano",
    "CKB": "Kurdish (Sorani)",
    "CS": "Czech",
    "CY": "Welsh",
    "DA": "Danish",
    "DE": "German",
    "EL": "Greek",
    "EN-GB": "English (British)",
    "EN-US": "English (American)",
    "EO": "Esperanto",
    "ES": "Spanish",
    "ES-419": "Spanish (Latin American)",
    "ET": "Estonian",
    "EU": "Basque",
    "FA": "Persian",
    "FI": "Finnish",
    "FR": "French",
    "GA": "Irish",
    "GL": "Galician",
    "GN": "Guarani",
    "GOM": "Konkani",
    "GU": "Gujarati",
    "HA": "Hausa",
    "HE": "Hebrew",
    "HI": "Hindi",
    "HR": "Croatian",
    "HT": "Haitian Creole",
    "HU": "Hungarian",
    "HY": "Armenian",
    "ID": "Indonesian",
    "IG": "Igbo",
    "IS": "Icelandic",
    "IT": "Italian",
    "JA": "Japanese",
    "JV": "Javanese",
    "KA": "Georgian",
    "KK": "Kazakh",
    "KMR": "Kurdish (Kurmanji)",
    "KO": "Korean",
    "KY": "Kyrgyz",
    "LA": "Latin",
    "LB": "Luxembourgish",
    "LMO": "Lombard",
    "LN": "Lingala",
    "LT": "Lithuanian",
    "LV": "Latvian",
    "MAI": "Maithili",
    "MG": "Malagasy",
    "MI": "Maori",
    "MK": "Macedonian",
    "ML": "Malayalam",
    "MN": "Mongolian",
    "MR": "Marathi",
    "MS": "Malay",
    "MT": "Maltese",
    "MY": "Burmese",
    "NB": "Norwegian Bokmål",
    "NE": "Nepali",
    "NL": "Dutch",
    "OC": "Occitan",
    "OM": "Oromo",
    "PA": "Punjabi",
    "PAG": "Pangasinan",
    "PAM": "Kapampangan",
    "PL": "Polish",
    "PRS": "Dari",
    "PS": "Pashto",
    "PT-BR": "Portuguese (Brazilian)",
    "PT-PT": "Portuguese",
    "QU": "Quechua",
    "RO": "Romanian",
    "RU": "Russian",
    "SA": "Sanskrit",
    "SCN": "Sicilian",
    "SK": "Slovak",
    "SL": "Slovenian",
    "SQ": "Albanian",
    "SR": "Serbian",
    "ST": "Sesotho",
    "SU": "Sundanese",
    "SV": "Swedish",
    "SW": "Swahili",
    "TA": "Tamil",
    "TE": "Telugu",
    "TG": "Tajik",
    "TH": "Thai",
    "TK": "Turkmen",
    "TL": "Tagalog",
    "TN": "Tswana",
    "TR": "Turkish",
    "TS": "Tsonga",
    "TT": "Tatar",
    "UK": "Ukrainian",
    "UR": "Urdu",
    "UZ": "Uzbek",
    "VI": "Vietnamese",
    "WO": "Wolof",
    "XH": "Xhosa",
    "YI": "Yiddish",
    "YUE": "Cantonese",
    "ZH-HANS": "Chinese (simplified)",
    "ZH-HANT": "Chinese (traditional)",
    "ZU": "Zulu",
  },
};

const sourceLanguages = ["Auto"];
const targetLanguages = [];
const language2acronym = {
  sources: {},
  targets: {},
};
for (const lang of Object.entries(acronym2language.sources)) {
  sourceLanguages.push(lang[1]);
  language2acronym.sources[lang[1]] = lang[0];
}
for (const lang of Object.entries(acronym2language.targets)) {
  targetLanguages.push(lang[1]);
  language2acronym.targets[lang[1]] = lang[0];
}

function translateCommand(text, sourceLang, targetLang, apiKey) {
  return [
    "curl",
    "-X",
    "POST",
    "https://api-free.deepl.com/v2/translate",
    "--header",
    `Authorization: DeepL-Auth-Key ${apiKey}`,
    "--header",
    "Content-Type: application/json",
    "--data",
    JSON.stringify({
      text: [text],
      source_lang: sourceLang.startsWith("Auto")
        ? ""
        : language2acronym.sources[sourceLang],
      target_lang: language2acronym.targets[targetLang],
    }),
  ];
}
