[Appearance]
color_scheme_path=/home/vitor/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Papirus-Dark

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2\xad\0\0\x3w\0\0\0\0\0\0\0\0\0\0\x2\xad\0\0\x3w\0\0\0\0\0\0\0\0\x5\xa0\0\0\0\0\0\0\0\0\0\0\x2\xad\0\0\x3w)
